// <auto-generated />
namespace Test_Project_IdentityMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeArrAvatar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeArrAvatar));
        
        string IMigrationMetadata.Id
        {
            get { return "202004270248592_changeArrAvatar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
